### ISSUE TITLE
comozilla-all@mozilla-japan.org が受信専用である旨を追記する

### ISSUE THREAD

**Issue by yammmt** [comozilla/comozilla.github.io#4]
返信出すときは専ら (というか例外なく) comozilla@gmail.com を使っているので、それを一行足した方が良いような気がします。  
特に、企業だとフリーメールへの送信を禁止しているところもちょくちょくあるっぽいので、 comozilla@gmail.com からの返信すら届かないケースも起こり得るのでは…？

**Comment by Babibubebon** [comment]
受信用アドレスについては、comozilla.orgドメインのメールアドレスを使えるように準備中ですが、
この件は一旦Closeさせてもらいますー
